export const locales = ["es", "en", "it"] as const;
export type Locale = (typeof locales)[number];
export function isLocale(value: string): value is Locale { return locales.includes(value as Locale); }
export const languageNames = { es: "Español", en: "English", it: "Italiano" };

const es = {
  nav: { home: "Inicio", services: "Servicios", how: "Cómo funciona", faq: "Preguntas frecuentes", cta: "Solicitar servicio", contact: "Contactar con Rooklyn", language: "Idioma", menu: "Abrir menú", close: "Cerrar", skip: "Saltar al contenido" },
  banner: "Estás explorando una demo interactiva de Rooklyn.", bannerCta: "Quiero este sistema para mi empresa",
  notice: "Demo interactiva creada por Rooklyn. Áurea Clima no presta servicios reales de climatización.",
  hero: { eyebrow: "Climatización sencilla y bien organizada", headline: "Confort en casa,", accent: "sin esperas innecesarias.", text: "Cuéntanos si necesitas una reparación o estás planificando una nueva instalación. Te guiaremos directamente al proceso adecuado.", repair: "Solicitar reparación", installation: "Solicitar instalación", micro: ["Proceso claro", "Reserva online", "Confirmación automática"], imageAlt: "Salón luminoso de estilo mediterráneo con un equipo de aire acondicionado en la pared y un sofá de lino claro.", imageLabel: "Tu hogar, a tu temperatura.", imageSub: "El confort empieza con un primer paso.", imageTag: "Pensado para tu hogar" },
  selection: { eyebrow: "EMPECEMOS POR LO QUE NECESITAS", title: "¿Qué necesitas?", text: "Dos caminos sencillos. Un mismo objetivo: tu confort.", repair: { title: "Reparación", text: "Indícanos qué equipo presenta el problema, la urgencia y cuándo prefieres recibir asistencia.", cta: "Empezar solicitud de reparación", tag: "Para un equipo que necesita atención" }, installation: { title: "Nueva instalación", text: "Cuéntanos qué sistema necesitas y reserva una visita técnica para evaluar el espacio.", cta: "Solicitar visita técnica", tag: "Para un nuevo comienzo en casa" }, maintenance: { title: "Mantenimiento", text: "Explora el proceso de reserva de mantenimiento de tu equipo.", cta: "Solicitar mantenimiento" } },
  overview: { eyebrow: "CADA HOGAR, UNA NECESIDAD", title: "Confort en todas sus formas.", text: "Estos son los tipos de solicitudes que esta demostración puede organizar.", cards: [{ title: "Aire acondicionado", text: "Reparación o instalación de equipos para mantener tu hogar fresco." }, { title: "Calefacción y calderas", text: "Solicitudes relacionadas con el calor y el agua caliente de tu hogar." }, { title: "Bombas de calor", text: "Información y visitas técnicas para un sistema de climatización integral." }, { title: "Mantenimiento preventivo", text: "Organización de revisiones y cuidado periódico de los equipos." }] },
  process: { eyebrow: "TODO CLARO, DESDE EL PRINCIPIO", title: "De tu solicitud a tu cita,\nen tres pasos.", text: "Así funciona el recorrido que puedes explorar en esta demo.", steps: [{ title: "Elige el servicio", text: "Selecciona reparación o instalación. Cada necesidad tiene su propio recorrido." }, { title: "Comparte la información esencial", text: "El formulario del recorrido recoge los detalles del equipo, la urgencia y tus datos de contacto." }, { title: "Selecciona una cita", text: "Elige un horario disponible en el calendario del recorrido y recibe la confirmación de la demo." }] },
  benefits: { title: "Menos gestiones.\nMás tranquilidad.", text: "Una experiencia pensada para que sepas qué hacer y qué viene después.", items: ["El servicio que necesitas, fácil de elegir", "Un recorrido adecuado para tu solicitud", "Tu cita, desde cualquier lugar", "Confirmaciones y recordatorios automáticos"] },
  faq: { eyebrow: "TE LO PONEMOS FÁCIL", title: "Resolvemos tus dudas.", text: "Lo esencial antes de dar el siguiente paso.", items: [{ q: "¿Debo elegir reparación o instalación?", a: "Elige reparación si un equipo existente presenta un problema. Elige instalación si quieres un equipo nuevo o sustituir el actual y explorar la reserva de una visita técnica." }, { q: "¿Qué información necesito facilitar?", a: "El recorrido puede pedirte el tipo de equipo, una descripción de tu necesidad, la urgencia, tu disponibilidad y datos de contacto. Esta es una demostración: evita incluir información sensible." }, { q: "¿Puedo elegir una cita online?", a: "Sí, cuando el calendario del recorrido esté conectado, podrás explorar sus horarios disponibles. No se reserva una intervención real de Áurea Clima." }, { q: "¿Se puede cambiar una cita?", a: "Si el calendario conectado permite cambios, encontrarás las instrucciones en la confirmación. La disponibilidad de esta opción depende de la configuración del recorrido." }, { q: "¿Áurea Clima es una empresa real de climatización?", a: "No. Áurea Clima es una marca de demostración creada por Rooklyn para mostrar una experiencia digital. No presta servicios reales de climatización." }, { q: "¿Esta demostración es gratuita?", a: "Puedes explorar esta web sin coste. No se venden servicios de climatización ni se solicitan pagos en esta página." }] },
  business: { eyebrow: "Para empresas de climatización", title: "¿Quieres ofrecer una experiencia\ncomo esta a tus clientes?", text: "Rooklyn conecta la captación, clasificación, reservas, seguimiento y mantenimiento en un sistema adaptado al proceso de tu empresa.", explore: "Explora Rooklyn", build: "Crea esto para mi empresa", primary: "Ver la solución de Rooklyn", secondary: "Solicitar un diagnóstico" },
  footer: { by: "Una experiencia creada por", back: "Descubre Rooklyn", privacy: "Política de privacidad", cookies: "Política de cookies", legal: "Aviso legal", settings: "Preferencias de cookies", tagline: "El confort empieza en casa.", demo: "Sitio de demostración" },
  consent: { title: "Tu privacidad, a tu manera.", text: "Usamos almacenamiento esencial para recordar tu idioma y tus preferencias. La analítica y el asistente opcional solo se activan si los aceptas.", accept: "Aceptar opcionales", reject: "Rechazar opcionales", customize: "Configurar", save: "Guardar preferencias", essential: "Esenciales", essentialText: "Idioma y preferencias de privacidad. Siempre activas.", analytics: "Analítica", analyticsText: "Permite medir el uso de la demo cuando la integración esté configurada.", functional: "Asistente opcional", functionalText: "Permite cargar el chat cuando esté disponible.", policy: "Consulta nuestras políticas:", required: "Siempre activas" },
  unavailable: { eyebrow: "RECORRIDO DE DEMOSTRACIÓN", title: "Tu recorrido empieza aquí.", text: "La solicitud externa todavía no está conectada a esta demostración. Puedes volver a explorar los servicios o descubrir cómo funciona el sistema de Rooklyn.", reassurance: "No se ha enviado ninguna solicitud ni reservado una cita.", back: "Volver a los servicios", consultation: "La solicitud de diagnóstico aún no está conectada. Puedes conocer la solución en la web de Rooklyn." },
  legal: { pending: "Información de esta demostración", intro: "Esta página describe el funcionamiento actual de la demo. Los documentos definitivos del responsable deben facilitarse y revisarse antes de una publicación comercial.", privacy: "Al seleccionar reparación o instalación se carga un formulario de GoHighLevel / LeadConnector. Los datos que introduzcas se gestionan en ese proveedor según la información del formulario. Esta demo no presta servicios ni acepta pagos. Guarda en tu dispositivo el idioma y tus preferencias de consentimiento. La analítica y el chat están desactivados hasta que se configuren y otorgues el consentimiento correspondiente.", cookies: "El almacenamiento esencial utiliza aureaclima_language y aureaclima_consent_v1 para recordar tus elecciones. La página no guarda atribución de campañas. El formulario externo se carga al elegir un servicio y puede utilizar almacenamiento propio. Sus controles de privacidad son independientes de las preferencias de analítica y chat de esta página. Puedes cambiar el consentimiento desde el pie de página o borrar estos datos en tu navegador. No se carga analítica ni chat sin tu consentimiento.", legal: "Áurea Clima es una marca ficticia de demostración creada por Rooklyn. No presta servicios, no acepta reservas reales y no representa a una empresa contratista. Los datos legales del responsable y los documentos definitivos aún deben ser suministrados.", back: "Volver al inicio" },
  error: { title: "No hemos podido cargar esta página.", text: "Vuelve a intentarlo o regresa al inicio para continuar explorando la demo.", retry: "Volver a intentar", missing: "Esta página no está disponible." }
};
export type Dictionary = typeof es;
const en: Dictionary = {
  nav: { home: "Home", services: "Services", how: "How it works", faq: "FAQs", cta: "Request Service", contact: "Contact Rooklyn", language: "Language", menu: "Open menu", close: "Close", skip: "Skip to content" },
  banner: "You are exploring an interactive Rooklyn demo.", bannerCta: "I want this system for my business",
  notice: "Interactive demonstration created by Rooklyn. Áurea Clima does not provide real HVAC services.",
  hero: { eyebrow: "Simple, organised climate-control service", headline: "Home comfort,", accent: "without unnecessary waiting.", text: "Tell us whether you need a repair or are planning a new installation. We will guide you directly to the appropriate process.", repair: "Request a repair", installation: "Request an installation", micro: ["Clear process", "Online booking", "Automatic confirmation"], imageAlt: "Sunlit Mediterranean living room with a wall-mounted air conditioner and a light linen sofa.", imageLabel: "Your home. Your comfort.", imageSub: "Comfort starts with a first step.", imageTag: "Designed around your home" },
  selection: { eyebrow: "LET’S START WITH WHAT YOU NEED", title: "How can we help?", text: "Two simple paths. One shared goal: your comfort.", repair: { title: "Repair", text: "Tell us which equipment has the problem, how urgent it is and when you would prefer assistance.", cta: "Start a repair request", tag: "For equipment that needs attention" }, installation: { title: "New installation", text: "Tell us which system you need and schedule a technical visit to assess the property.", cta: "Request a technical visit", tag: "For a fresh start at home" }, maintenance: { title: "Maintenance", text: "Explore the appointment journey for your equipment’s maintenance.", cta: "Request maintenance" } },
  overview: { eyebrow: "EVERY HOME HAS ITS NEEDS", title: "Comfort in all its forms.", text: "These are the types of requests this demonstration can organise.", cards: [{ title: "Air conditioning", text: "Repair or installation requests to keep your home cool." }, { title: "Heating and boilers", text: "Requests related to your home’s heating and hot water." }, { title: "Heat pumps", text: "Information and technical visits for a complete climate-control system." }, { title: "Preventive maintenance", text: "Organising inspections and regular care for equipment." }] },
  process: { eyebrow: "CLEAR FROM THE VERY BEGINNING", title: "From request to appointment,\nin three steps.", text: "Here is the journey you can explore in this demo.", steps: [{ title: "Choose the service", text: "Select repair or installation. Each need has its own journey." }, { title: "Share the essential information", text: "The journey’s form collects equipment details, urgency and your contact information." }, { title: "Choose an appointment", text: "Choose an available time in the journey’s calendar and receive a demonstration confirmation." }] },
  benefits: { title: "Less organising.\nMore peace of mind.", text: "An experience designed to help you know what to do and what comes next.", items: ["The service you need, easy to choose", "The right journey for your request", "Book your appointment from anywhere", "Automatic confirmations and reminders"] },
  faq: { eyebrow: "LET’S KEEP THINGS SIMPLE", title: "Your questions, answered.", text: "The essentials before you take the next step.", items: [{ q: "Should I choose repair or installation?", a: "Choose repair if an existing unit has a problem. Choose installation if you want a new system or a replacement and would like to explore booking a technical visit." }, { q: "What information will I need to provide?", a: "The journey may ask for the equipment type, a description of your needs, urgency, availability and contact details. This is a demonstration: avoid including sensitive information." }, { q: "Can I select an appointment online?", a: "Yes, once the journey’s calendar is connected, you can explore its available times. You are not booking a real Áurea Clima service visit." }, { q: "Can an appointment be rescheduled?", a: "If the connected calendar supports changes, the confirmation will include instructions. This option depends on the journey’s configuration." }, { q: "Is Áurea Clima a real HVAC company?", a: "No. Áurea Clima is a demonstration brand created by Rooklyn to show a digital customer experience. It does not provide real HVAC services." }, { q: "Is this demonstration free?", a: "You can explore this website free of charge. No HVAC services are sold and no payments are requested on this page." }] },
  business: { eyebrow: "For HVAC businesses", title: "Would you like to offer your customers\nan experience like this?", text: "Rooklyn connects lead capture, qualification, booking, follow-up and maintenance in a system adapted to your company’s process.", explore: "Explore Rooklyn", build: "Build this for my business", primary: "See the Rooklyn solution", secondary: "Request an assessment" },
  footer: { by: "An experience created by", back: "Discover Rooklyn", privacy: "Privacy Policy", cookies: "Cookie Policy", legal: "Legal Notice", settings: "Cookie preferences", tagline: "Comfort starts at home.", demo: "Demonstration website" },
  consent: { title: "Your privacy, your choice.", text: "We use essential storage to remember your language and preferences. Analytics and the optional assistant only activate if you accept them.", accept: "Accept optional", reject: "Reject optional", customize: "Preferences", save: "Save preferences", essential: "Essential", essentialText: "Language and privacy preferences. Always active.", analytics: "Analytics", analyticsText: "Allows demo usage measurement once the integration is configured.", functional: "Optional assistant", functionalText: "Allows chat to load when available.", policy: "Read our policies:", required: "Always active" },
  unavailable: { eyebrow: "DEMONSTRATION JOURNEY", title: "Your journey starts here.", text: "The external request journey is not yet connected to this demonstration. You can explore the services again or discover how the Rooklyn system works.", reassurance: "No request has been submitted and no appointment has been booked.", back: "Back to services", consultation: "The assessment request is not connected yet. You can learn about the solution on Rooklyn’s website." },
  legal: { pending: "About this demonstration", intro: "This page describes the demo’s current operation. The controller’s final documents must be supplied and reviewed before commercial publication.", privacy: "Selecting repair or installation loads a GoHighLevel / LeadConnector form. Information you enter is handled by that provider under the information shown in the form. This demo provides no services and accepts no payments. It stores your language and consent preferences on your device. Analytics and chat remain disabled until configured and you provide the relevant consent.", cookies: "Essential storage uses aureaclima_language and aureaclima_consent_v1 to remember your choices. The page does not store campaign attribution. The external form loads when you choose a service and may use its own storage. Its privacy controls are separate from this page’s analytics and chat preferences. You can change consent from the footer or clear this data in your browser. Analytics and chat do not load without your consent.", legal: "Áurea Clima is a fictional demonstration brand created by Rooklyn. It provides no services, accepts no real bookings and does not represent an HVAC contractor. The controller’s legal details and final documents still need to be supplied.", back: "Back to home" },
  error: { title: "We couldn’t load this page.", text: "Try again or return home to continue exploring the demo.", retry: "Try again", missing: "This page is not available." }
};
const it: Dictionary = {
  nav: { home: "Home", services: "Servizi", how: "Come funziona", faq: "Domande frequenti", cta: "Richiedi un servizio", contact: "Contatta Rooklyn", language: "Lingua", menu: "Apri menu", close: "Chiudi", skip: "Vai al contenuto" },
  banner: "Stai esplorando una demo interattiva di Rooklyn.", bannerCta: "Voglio questo sistema per la mia azienda",
  notice: "Dimostrazione interattiva creata da Rooklyn. Áurea Clima non fornisce servizi reali di climatizzazione.",
  hero: { eyebrow: "Un servizio di climatizzazione semplice e organizzato", headline: "Comfort in casa,", accent: "senza attese inutili.", text: "Dicci se hai bisogno di una riparazione o se stai pianificando una nuova installazione. Ti guideremo direttamente al percorso corretto.", repair: "Richiedi una riparazione", installation: "Richiedi un’installazione", micro: ["Processo chiaro", "Prenotazione online", "Conferma automatica"], imageAlt: "Soggiorno mediterraneo luminoso con un climatizzatore a parete e un divano in lino chiaro.", imageLabel: "La tua casa, il tuo comfort.", imageSub: "Il comfort inizia con un primo passo.", imageTag: "Pensato per la tua casa" },
  selection: { eyebrow: "PARTIAMO DA CIÒ CHE TI SERVE", title: "Di cosa hai bisogno?", text: "Due percorsi semplici. Un unico obiettivo: il tuo comfort.", repair: { title: "Riparazione", text: "Indicaci quale apparecchiatura presenta il problema, il livello di urgenza e quando preferisci ricevere assistenza.", cta: "Inizia una richiesta di riparazione", tag: "Per un impianto che richiede attenzione" }, installation: { title: "Nuova installazione", text: "Indicaci quale sistema ti serve e prenota una visita tecnica per valutare l’immobile.", cta: "Richiedi una visita tecnica", tag: "Per un nuovo inizio a casa" }, maintenance: { title: "Manutenzione", text: "Esplora il percorso di prenotazione per la manutenzione del tuo impianto.", cta: "Richiedi manutenzione" } },
  overview: { eyebrow: "OGNI CASA, UN’ESIGENZA", title: "Il comfort, in tutte le sue forme.", text: "Questi sono i tipi di richieste che questa dimostrazione può organizzare.", cards: [{ title: "Aria condizionata", text: "Richieste di riparazione o installazione per una casa fresca." }, { title: "Riscaldamento e caldaie", text: "Richieste per il riscaldamento e l’acqua calda della tua casa." }, { title: "Pompe di calore", text: "Informazioni e visite tecniche per un sistema di climatizzazione completo." }, { title: "Manutenzione preventiva", text: "Organizzazione di controlli e cura periodica degli impianti." }] },
  process: { eyebrow: "TUTTO CHIARO, FIN DALL’INIZIO", title: "Dalla richiesta all’appuntamento,\nin tre passi.", text: "Ecco il percorso che puoi esplorare in questa demo.", steps: [{ title: "Scegli il servizio", text: "Seleziona riparazione o installazione. Ogni esigenza ha il suo percorso." }, { title: "Condividi le informazioni essenziali", text: "Il modulo del percorso raccoglie i dettagli dell’impianto, l’urgenza e i tuoi recapiti." }, { title: "Scegli un appuntamento", text: "Scegli un orario disponibile nel calendario del percorso e ricevi una conferma dimostrativa." }] },
  benefits: { title: "Meno impegni.\nPiù tranquillità.", text: "Un’esperienza pensata per sapere cosa fare e cosa succederà dopo.", items: ["Il servizio che ti serve, facile da scegliere", "Il percorso adatto alla tua richiesta", "Il tuo appuntamento, da qualsiasi luogo", "Conferme e promemoria automatici"] },
  faq: { eyebrow: "RENDIAMO LE COSE SEMPLICI", title: "Rispondiamo ai tuoi dubbi.", text: "L’essenziale prima del prossimo passo.", items: [{ q: "Devo scegliere riparazione o installazione?", a: "Scegli riparazione se un impianto esistente presenta un problema. Scegli installazione per un impianto nuovo o una sostituzione e per esplorare la prenotazione di una visita tecnica." }, { q: "Quali informazioni devo fornire?", a: "Il percorso può chiederti il tipo di impianto, una descrizione della necessità, l’urgenza, la disponibilità e i recapiti. È una dimostrazione: evita di inserire informazioni sensibili." }, { q: "Posso scegliere un appuntamento online?", a: "Sì, quando il calendario del percorso sarà collegato, potrai esplorare gli orari disponibili. Non si prenota un vero intervento di Áurea Clima." }, { q: "È possibile riprogrammare un appuntamento?", a: "Se il calendario collegato permette modifiche, le istruzioni saranno incluse nella conferma. Questa opzione dipende dalla configurazione del percorso." }, { q: "Áurea Clima è una vera azienda di climatizzazione?", a: "No. Áurea Clima è un marchio dimostrativo creato da Rooklyn per mostrare un’esperienza digitale. Non fornisce servizi reali di climatizzazione." }, { q: "Questa dimostrazione è gratuita?", a: "Puoi esplorare questo sito gratuitamente. Su questa pagina non si vendono servizi di climatizzazione e non si richiedono pagamenti." }] },
  business: { eyebrow: "Per le aziende di climatizzazione", title: "Vuoi offrire ai tuoi clienti\nun’esperienza come questa?", text: "Rooklyn collega acquisizione, qualificazione, prenotazioni, follow-up e manutenzione in un sistema adattato ai processi della tua azienda.", explore: "Esplora Rooklyn", build: "Crea questo per la mia azienda", primary: "Scopri la soluzione Rooklyn", secondary: "Richiedi una valutazione" },
  footer: { by: "Un’esperienza creata da", back: "Scopri Rooklyn", privacy: "Informativa sulla privacy", cookies: "Informativa sui cookie", legal: "Note legali", settings: "Preferenze cookie", tagline: "Il comfort inizia a casa.", demo: "Sito dimostrativo" },
  consent: { title: "La tua privacy, la tua scelta.", text: "Usiamo l’archiviazione essenziale per ricordare lingua e preferenze. L’analisi e l’assistente opzionale si attivano solo se li accetti.", accept: "Accetta opzionali", reject: "Rifiuta opzionali", customize: "Preferenze", save: "Salva preferenze", essential: "Essenziali", essentialText: "Lingua e preferenze di privacy. Sempre attivi.", analytics: "Analisi", analyticsText: "Permette di misurare l’uso della demo quando l’integrazione è configurata.", functional: "Assistente opzionale", functionalText: "Permette di caricare la chat quando disponibile.", policy: "Leggi le nostre informative:", required: "Sempre attivi" },
  unavailable: { eyebrow: "PERCORSO DIMOSTRATIVO", title: "Il tuo percorso inizia qui.", text: "La richiesta esterna non è ancora collegata a questa dimostrazione. Puoi tornare a esplorare i servizi o scoprire come funziona il sistema di Rooklyn.", reassurance: "Non è stata inviata alcuna richiesta né prenotato un appuntamento.", back: "Torna ai servizi", consultation: "La richiesta di valutazione non è ancora collegata. Puoi conoscere la soluzione sul sito di Rooklyn." },
  legal: { pending: "Informazioni sulla dimostrazione", intro: "Questa pagina descrive il funzionamento attuale della demo. I documenti definitivi del titolare devono essere forniti e verificati prima di una pubblicazione commerciale.", privacy: "Selezionando riparazione o installazione si carica un modulo di GoHighLevel / LeadConnector. I dati inseriti sono gestiti dal fornitore secondo le informazioni del modulo. Questa demo non fornisce servizi né accetta pagamenti. Salva sul tuo dispositivo la lingua e le preferenze di consenso. Analisi e chat restano disattivate finché non sono configurate e non fornisci il consenso corrispondente.", cookies: "L’archiviazione essenziale usa aureaclima_language e aureaclima_consent_v1 per ricordare le tue scelte. La pagina non salva i dati di attribuzione delle campagne. Il modulo esterno si carica quando scegli un servizio e può usare un proprio archivio. I suoi controlli sulla privacy sono separati dalle preferenze di analisi e chat di questa pagina. Puoi cambiare il consenso dal piè di pagina o cancellare questi dati nel browser. Analisi e chat non si caricano senza il tuo consenso.", legal: "Áurea Clima è un marchio fittizio dimostrativo creato da Rooklyn. Non fornisce servizi, non accetta prenotazioni reali e non rappresenta un’impresa di climatizzazione. I dati legali del titolare e i documenti definitivi devono ancora essere forniti.", back: "Torna alla home" },
  error: { title: "Non è stato possibile caricare la pagina.", text: "Riprova o torna alla home per continuare a esplorare la demo.", retry: "Riprova", missing: "Questa pagina non è disponibile." }
};
export const dictionaries: Record<Locale, Dictionary> = { es, en, it };
