import Image from "next/image";
import { notFound } from "next/navigation";
import { dictionaries, isLocale } from "@/i18n/dictionaries";
import { LowerSections } from "@/components/lower-sections";
import { JourneyLink } from "@/components/navigation";
import { Icon } from "@/components/icon";
export default async function Home({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const d = dictionaries[locale];
  return <><main id="main"><section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow hero-eyebrow"><span/>{d.hero.eyebrow}</p><h1>{d.hero.headline}<br/><span>{d.hero.accent}</span></h1><p className="hero-description">{d.hero.text}</p><div className="hero-buttons"><JourneyLink destination="repair" locale={locale} className="button button-gold" placement="hero">{d.hero.repair}<Icon name="arrow" size={19}/></JourneyLink><JourneyLink destination="installation" locale={locale} className="button button-outline" placement="hero">{d.hero.installation}<Icon name="arrow" size={19}/></JourneyLink></div><div className="hero-micro">{d.hero.micro.map(text => <span key={text}><Icon name="check" size={14}/>{text}</span>)}</div></div><div className="hero-visual"><div className="hero-image"><Image src="/images/home-comfort.png" alt={d.hero.imageAlt} fill priority sizes="(max-width: 767px) 92vw, (max-width: 1200px) 46vw, 550px"/><span className="image-tag"><Icon name="leaf" size={16}/>{d.hero.imageTag}</span></div><div className="comfort-note"><span className="comfort-icon"><Icon name="home" size={25}/></span><span><strong>{d.hero.imageLabel}</strong><small>{d.hero.imageSub}</small></span><span className="note-check"><Icon name="check" size={15}/></span></div><span className="image-corner"/></div></div></section><section className="section selection" id="services"><div className="container"><div className="section-heading centered"><p className="eyebrow">{d.selection.eyebrow}</p><h2>{d.selection.title}</h2><p>{d.selection.text}</p></div><div className="selection-grid">{(["repair", "installation"] as const).map((service, index) => <article className={`service-card service-${service}`} key={service}><div className="card-top"><span className="service-icon"><Icon name={service === "repair" ? "repair" : "home"} size={27}/></span><span className="card-number">0{index + 1}</span></div><p className="service-tag">{d.selection[service].tag}</p><h3>{d.selection[service].title}</h3><p>{d.selection[service].text}</p><JourneyLink destination={service} locale={locale} className={`button ${service === "repair" ? "button-navy" : "button-teal"}`} placement="services">{d.selection[service].cta}<Icon name="arrow" size={20}/></JourneyLink></article>)}</div><p className="section-demo"><Icon name="shield" size={16}/>{d.notice}</p></div></section><LowerSections locale={locale} d={d}/></main></>;
}
